[tool.poetry]
name = "rehline"
version = "0.0.3"
description = "Regularized Composite ReLU-ReHU Loss Minimization with Linear Computation and Linear Convergence"
authors = ["Ben Dai <bendai@cuhk.edu.hk>", "Yixuan Qiu <yixuanq@gmail.com>"]
maintainers = ["Ben Dai <bendai@cuhk.edu.hk>"]
license = "MIT"
readme = "README.md"
homepage = "https://rehline.github.io/"
repository = "https://github.com/softmin/ReHLine-python"
documentation = "https://rehline-python.readthedocs.io/en/latest/index.html"
include = [
    {path = "rehline/*.so", format = "wheel"}
]

[tool.poetry.build]
script = "build.py"
generate-setup-file = false

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.18.0"
pybind11 = "^2.11.1"
numpy = "^1.23.5"
scipy = "^1.11.4"
scikit-learn = "^1.2.2"

[build-system]
requires = ["poetry-core>=1.0.0", "requests ~= 2.31.0", "pybind11 ~= 2.11.1", "setuptools ~= 59.0"]
build-backend = "poetry.core.masonry.api" 